### PR TITLE
Simultaneous Promscale versions

### PR DESCRIPTION
**Pull request by sumerman**
Addresses https://github.com/timescale/promscale_extension/issues/113

### CODE REVIEW

**Comment by feikesteenbergen** [comment]
Thanks! I had a deeper dive into the cicd built Docker Image, and I can only find a single `promscale.so` for all the versions, which means this is probably not doing what it should be doing.

That probably means the following:

- only the *latest* `promscale.so is included in the image
- all the *sql* files for the other versions do exist

Compare for example, this is using the Docker Image that was built against your PR:

```bash
docker run -ti ********.dkr.ecr.us-east-1.amazonaws.com/timescaledb-ha:cicd-230f8649 bash
```

Every TimescaleDB version that was compiled has its own `.so` file, that allows us to run different versions for different users.

```bash
postgres@fa08d466c07e:/usr/lib/postgresql/14/lib$ ls -l /usr/lib/postgresql/14/lib/timescaledb-*.so
-rw-r--r-- 1 postgres postgres 4223928 Apr 18 17:19 /usr/lib/postgresql/14/lib/timescaledb-2.5.0.so
-rw-r--r-- 1 postgres postgres 4221152 Apr 18 17:20 /usr/lib/postgresql/14/lib/timescaledb-2.5.1.so
-rw-r--r-- 1 postgres postgres 4225240 Apr 18 17:20 /usr/lib/postgresql/14/lib/timescaledb-2.5.2.so
-rw-r--r-- 1 postgres postgres 4368632 Apr 18 17:21 /usr/lib/postgresql/14/lib/timescaledb-2.6.0.so
-rw-r--r-- 1 postgres postgres 4430504 Apr 18 17:21 /usr/lib/postgresql/14/lib/timescaledb-2.6.1.so
-rw-r--r-- 1 postgres postgres 4506888 Apr 18 17:19 /usr/lib/postgresql/14/lib/timescaledb-tsl-2.5.0.so
-rw-r--r-- 1 postgres postgres 4544440 Apr 18 17:20 /usr/lib/postgresql/14/lib/timescaledb-tsl-2.5.1.so
-rw-r--r-- 1 postgres postgres 4552216 Apr 18 17:20 /usr/lib/postgresql/14/lib/timescaledb-tsl-2.5.2.so
-rw-r--r-- 1 postgres postgres 4593128 Apr 18 17:21 /usr/lib/postgresql/14/lib/timescaledb-tsl-2.6.0.so
-rw-r--r-- 1 postgres postgres 4595512 Apr 18 17:21 /usr/lib/postgresql/14/lib/timescaledb-tsl-2.6.1.so
```

```bash
postgres@fa08d466c07e:/usr/lib/postgresql/14/lib$ ls -l /usr/lib/postgresql/14/lib/promscale*.so
-rwxr-xr-x 1 postgres postgres 1663152 Apr 18 17:41 /usr/lib/postgresql/14/lib/promscale.so
```

Other extensions that *do* differ between versions is for example, `timescaledb_toolkit`:
```bash
postgres@fa08d466c07e:/usr/lib/postgresql/14/lib$ ls -l /usr/lib/postgresql/14/lib/timescaledb_toolkit*.so
-rwxr-xr-x 1 postgres postgres 90153376 Apr 18 17:55 /usr/lib/postgresql/14/lib/timescaledb_toolkit-1.5.1.so
-rwxr-xr-x 1 postgres postgres 93012824 Apr 18 18:01 /usr/lib/postgresql/14/lib/timescaledb_toolkit-1.6.0.so
```

The `sql` install files will then point to a *specific version specified* `.so` file:

```bash
postgres@66a9711da799:/usr/share/postgresql/14/extension$ grep '$libdir/timescaledb_toolkit' timescaledb_toolkit--1.5.1.sql | head -n 1
AS '$libdir/timescaledb_toolkit-1.5.1', 'generate_periodic_normal_series_wrapper';
postgres@66a9711da799:/usr/share/postgresql/14/extension$ grep '$libdir/timescaledb_toolkit' timescaledb_toolkit--1.6.0.sql | head -n 1
```

Or, the `.control` file will have the [`module_pathname`](https://www.postgresql.org/docs/current/extend-extensions.html) specified:
```bash
postgres@66a9711da799:/usr/share/postgresql/14/extension$ grep module_pathname timescaledb.control
timescaledb.control:module_pathname = '$libdir/timescaledb-2.6.1'
```

**Comment by sumerman** [comment]
> Thanks! I had a deeper dive into the cicd built Docker Image, and I can only find a single `promscale.so` for all the versions, which means this is probably not doing what it should be doing.
> 
> That probably means the following:
> 
> * only the _latest_ `promscale.so is included in the image
> * all the _sql_ files for the other versions do exist
> 
> Compare for example, this is using the Docker Image that was built against your PR:
> 
> ```shell
> docker run -ti ********.dkr.ecr.us-east-1.amazonaws.com/timescaledb-ha:cicd-230f8649 bash
> ```
> 
> Every TimescaleDB version that was compiled has its own `.so` file, that allows us to run different versions for different users.
> 
> ```shell
> postgres@fa08d466c07e:/usr/lib/postgresql/14/lib$ ls -l /usr/lib/postgresql/14/lib/timescaledb-*.so
> -rw-r--r-- 1 postgres postgres 4223928 Apr 18 17:19 /usr/lib/postgresql/14/lib/timescaledb-2.5.0.so
> -rw-r--r-- 1 postgres postgres 4221152 Apr 18 17:20 /usr/lib/postgresql/14/lib/timescaledb-2.5.1.so
> -rw-r--r-- 1 postgres postgres 4225240 Apr 18 17:20 /usr/lib/postgresql/14/lib/timescaledb-2.5.2.so
> -rw-r--r-- 1 postgres postgres 4368632 Apr 18 17:21 /usr/lib/postgresql/14/lib/timescaledb-2.6.0.so
> -rw-r--r-- 1 postgres postgres 4430504 Apr 18 17:21 /usr/lib/postgresql/14/lib/timescaledb-2.6.1.so
> -rw-r--r-- 1 postgres postgres 4506888 Apr 18 17:19 /usr/lib/postgresql/14/lib/timescaledb-tsl-2.5.0.so
> -rw-r--r-- 1 postgres postgres 4544440 Apr 18 17:20 /usr/lib/postgresql/14/lib/timescaledb-tsl-2.5.1.so
> -rw-r--r-- 1 postgres postgres 4552216 Apr 18 17:20 /usr/lib/postgresql/14/lib/timescaledb-tsl-2.5.2.so
> -rw-r--r-- 1 postgres postgres 4593128 Apr 18 17:21 /usr/lib/postgresql/14/lib/timescaledb-tsl-2.6.0.so
> -rw-r--r-- 1 postgres postgres 4595512 Apr 18 17:21 /usr/lib/postgresql/14/lib/timescaledb-tsl-2.6.1.so
> ```
> 
>  ```shell
> postgres@fa08d466c07e:/usr/lib/postgresql/14/lib$ ls -l /usr/lib/postgresql/14/lib/promscale*.so
> -rwxr-xr-x 1 postgres postgres 1663152 Apr 18 17:41 /usr/lib/postgresql/14/lib/promscale.so
> ```
> 
> Other extensions that _do_ differ between versions is for example, `timescaledb_toolkit`:
> 
> ```shell
> postgres@fa08d466c07e:/usr/lib/postgresql/14/lib$ ls -l /usr/lib/postgresql/14/lib/timescaledb_toolkit*.so
> -rwxr-xr-x 1 postgres postgres 90153376 Apr 18 17:55 /usr/lib/postgresql/14/lib/timescaledb_toolkit-1.5.1.so
> -rwxr-xr-x 1 postgres postgres 93012824 Apr 18 18:01 /usr/lib/postgresql/14/lib/timescaledb_toolkit-1.6.0.so
> ```
> 
> The `sql` install files will then point to a _specific version specified_ `.so` file:
> 
> ```shell
> postgres@66a9711da799:/usr/share/postgresql/14/extension$ grep '$libdir/timescaledb_toolkit' timescaledb_toolkit--1.5.1.sql | head -n 1
> AS '$libdir/timescaledb_toolkit-1.5.1', 'generate_periodic_normal_series_wrapper';
> postgres@66a9711da799:/usr/share/postgresql/14/extension$ grep '$libdir/timescaledb_toolkit' timescaledb_toolkit--1.6.0.sql | head -n 1
> ```
> 
> Or, the `.control` file will have the [`module_pathname`](https://www.postgresql.org/docs/current/extend-extensions.html) specified:
> 
> ```shell
> postgres@66a9711da799:/usr/share/postgresql/14/extension$ grep module_pathname timescaledb.control
> timescaledb.control:module_pathname = '$libdir/timescaledb-2.6.1'
> ```

I rolled back to include a single stable version. While I was testing I set `TIMESCALE_PROMSCALE_EXTENSIONS?=0.3.2 develop`,  not it's only `0.3.2`

**Comment by sumerman** [comment]
@feikesteenbergen I just realized `cicd-ec5c7a55` is still around and you can poke at it. It's the image built before I rewrote the commit with just a single version.

**Comment by feikesteenbergen** [comment]
LGTM:

```
postgres@2ae66d6188a5:~$ find /usr/lib/postgresql/14/lib/ -name '*promscale*so'
/usr/lib/postgresql/14/lib/promscale-0.5.0.so
/usr/lib/postgresql/14/lib/promscale.so
```

**Review by feikesteenbergen — APPROVED** [review]

**Pull request merged**
