### PR TITLE
Added Barman Cloud for CloudNativePG compatibility

### LINKED ISSUE #422: Database cluster compatible image
Would you accept a PR with an amendment to your docker image so that it supports database cluster via Kubernetes operators (such as [CloudNativePG](https://cloudnative-pg.io/))?

The image would need to include [Barman](https://pgbarman.org/) for backups and optionally the following extensions:

* `pgaudit`
* `pg-failover-slots`

Currently there are a couple of images from community members, and the community will benefit a lot from an official image they can trust.

### PR DESCRIPTION
**Pull request by itay-grudev**
Closes #422

### CODE REVIEW

**Review by graveland — APPROVED** [review]
lgtm!

**Comment by graveland** [comment]
(by the way, it's been standard practice that the PR author merges things)

**Comment by itay-grudev** [comment]
@graveland I don't have access to that, as a third-party contributor.

**Comment by graveland** [comment]
> @graveland I don't have access to that, as a third-party contributor.

Ha! sorry about that :)

**Pull request merged**
