### PR TITLE
Add patroni-k8s-sync callback CLI

### PR DESCRIPTION
**Pull request by thedodd**
This CLI synchronizes data from Patroni with a host K8s cluster,
particularly in cases where Patroni is not using the host K8s
cluster as its DCS.

### CODE REVIEW

**Comment by thedodd** [comment]
First item to adjust: where should this binary go? Perhaps I’ll put it next to hot-forge … will investigate.

**Comment by thedodd** [comment]
Ok, updated per slack discussion. I forgot to publish the actual release of patroni-k8s-sync, so it should work now.

**Comment by thedodd** [comment]
Very nice. I pulled the image, re-tagged with a slightly more permanent tag for long-term testing, tested out the callback, and it is all working as expected. Adds a few MiBs to the image, but that's about it.

**Review by graveland — APPROVED** [review]
lgtm

**Review by alexeyklyukin — APPROVED** [review]
Looks good!

**Review by feikesteenbergen — APPROVED** [review]

**Pull request merged**
