### PR TITLE
Fix a couple missing images

### LINKED ISSUE #367: TimescaleDB Community container images for PostgreSQL 14.7 are missing
It seems that container images of "TSDB Community" for PostgreSQL 14.7 are missing in Docker Hub.

For example:
```sh
$ docker pull timescale/timescaledb-ha:pg14.7-ts2.10.0-latest
Error response from daemon: manifest for timescale/timescaledb-ha:pg14.7-ts2.10.0-latest not found: manifest unknown: manifest unknown
$ docker pull timescale/timescaledb-ha:pg14.7-ts2.9.3-latest
Error response from daemon: manifest for timescale/timescaledb-ha:pg14.7-ts2.9.3-latest not found: manifest unknown: manifest unknown
```

There are OSS images though:

```sh
$ docker pull timescale/timescaledb-ha:pg14.7-ts2.10.0-oss-latest
pg14.7-ts2.10.0-oss-latest: Pulling from timescale/timescaledb-ha
(...)
$ docker pull timescale/timescaledb-ha:pg14.7-ts2.9.3-oss-latest
pg14.7-ts2.9.3-oss-latest: Pulling from timescale/timescaledb-ha
(...)
```

There is also a "TSDB Community" image for PostgreSQL 15.2 (== the latest PostgreSQL):

```sh
$ docker pull timescale/timescaledb-ha:pg15.2-ts2.10.0-latest
pg15.2-ts2.10.0-latest: Pulling from timescale/timescaledb-ha
(...)
```

I don't know whether this is intentional and only the most recent Postgres is supported, but I haven't found any mention of it in the docs. Please if it's possible, can you also build these missing container images for PostgreSQL 14.7?

Thank you.

### PR DESCRIPTION
**Pull request by graveland**
Fixes #367 and #363

### CODE REVIEW

**Review by alexeyklyukin — APPROVED** [review]
Looks good!

**Comment by udesaiitrs** [comment]
@graveland thanks for the fix, will this be released soon / missing docker images published?

**Comment by graveland** [comment]
> @graveland thanks for the fix, will this be released / missing docker images published soon?

Hopefully today!

**Comment by graveland** [comment]
Check now

**Comment by udesaiitrs** [comment]
@graveland It's there, thanks so much! [pg14.7-ts2.10.1-p1](https://hub.docker.com/layers/timescale/timescaledb-ha/pg14.7-ts2.10.1-p1/images/sha256-1d9729ee085fb20bab18e64bfe80b62afb0b21b2f9a04bed4b739c65fe00dd78?context=explore)

**Pull request merged**
