### PR TITLE
PostgreSQL 17 support

### PR DESCRIPTION
**Pull request by graveland**
related to https://github.com/timescale/forge-issues/issues/1364

### CODE REVIEW

**Review by fabriziomello — APPROVED** [review]
LGTM

**Comment by parasol-me** [comment]
Cant wait for this! :pray:

**Comment by mertbakir** [comment]
why can't we get this?

**Comment by skreborn** [comment]
According to this [comment](https://github.com/tensorchord/pgvecto.rs/issues/607#issuecomment-2484589971), pgvecto.rs has just come out with a release supporting PostgreSQL 17 - although it isn't available on their GitHub releases page yet as of this moment.

**Pull request merged**
